### ISSUE TITLE
Allow regexp in table cells

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin3#113]
Like `username:\s+xyz` - see comments in [this blog post](https://cucumber.io/blog/2015/09/11/cucumber-2.1)

Might be relevant to #40 and #71

**Comment by brasmusson** [comment]
To me it looks like the current implementation use the following handling of "\":
`\n` -> `newline`
`\|` -> `|`
`\<other>` -> `<other>`
What is the behavior we want?
`\n` -> `newline`
`\|` -> `|`
`\<other>` -> `\<other>`
or
`\n` -> `newline`
`\|` -> `|`
`\s` -> `\s`  (and the same for the other regexp expressions)
`\<other>` -> `<other>`

**Comment by akostadinov** [comment]
To me most important for implementation allow extensibility without breaking compatibility. If we escape only `|`, `n` and `\`, then that might make gherkin3 be more compatible with gherkin2. But what if other escapes are desired in the future? For example unicode escapes might be added in the future and other stuff.
That's why my vote goes to leave current implementation. It will be one time migration hassle but for more flexibility later.

**Comment by aslakhellesoy** [comment]
@akostadinov why would we need to support escaping of unicode characters when they can be written as-is?

**Comment by akostadinov** [comment]
Sometimes it's inconvenient to insert character as is. `tab` can be transformed by code editors into spaces, some people may need CR+LF, some characters might not be found in common fonts or you don't have them on your keyboard and pasting not easy (e.g. over vnc session).

As I said, any more exotic transformation can be handled in `Transform` so I'm ok with what works for most users.

**Comment by aslakhellesoy** [comment]
Fixed on master
