### ISSUE TITLE
Data Table differs from Scenario Outline's Example Table

### ISSUE THREAD

**Issue by rianby64** [cucumber/gherkin3#141]
I'm currently using https://github.com/cucumber/gherkin3 under JavaScript. This tool is amazing!
But, I can't understand one thing...

I read the documentation about data tables here> https://cucumber.io/docs/reference#data-tables
And the given table is being parsed not like a table with variables. Lets consider:

```cucumber
Examples:
  | name   | email              | twitter         |
  | Aslak  | aslak@cucumber.io  | @aslak_hellesoy |
  | Julien | julien@cucumber.io | @jbpros         |
  | Matt   | matt@cucumber.io   | @mattwynne      |
```
If I use this table like an example for an "Scenario Outline" then I have

```javascript
// An object type "Examples" that contains an attribute
tableHeader = [ "name", "email", "twitter" ] // 
```
and

```javascript
// and a second attribute
tableBody = [
    { name: Aslak, email: aslak@cucumber.io, twitter: @aslak_hellesoy },
    { name: Julien, email: julien@cucumber.io, twitter: @jbpros },
    { name: Matt, email: matt@cucumber.io, twitter: @mattwynne }
]
```
But if parsing Data Table I have just a set of TableRows without variable naming.
So... parsing Data Tables should be similar to Examples?

If not, then how to assign the columns to a set of variables in a Data Table?

Here's an example
```cucumber
Feature: Outline site support

  Scenario Outline: eating <start> <eat> <left>
    Given there are <start> cucumbers <other>
      | other |
      |   x   |
      |   y   |
      |   z   |
    When I eat <eat> cucumbers
    Then I should have <left> cucumbers

    Examples:
      | start | eat | left |
      |  12   |  5  |  7   |
      |  20   |  5  |  15  |
```

Thanks a lot!

**Comment by aslakhellesoy** [comment]
Examples tables and Data Tables have the same syntax, but they are semantically different. Their AST representations are different because they have a different purpose.

Example tables always have a header row, because the compiler needs to match the header columns to the placeholders in the Scenario Outline's steps.

Data tables are passed wholesale to the step definitions, and it's up to the user to interpret them. They don't necessarily have a header row:

```gherkin
Given the following tic tac toe board:
  | x |   |   |
  | o | x |   |
  | x |   | o |
```

Since they have different purposes and semantics, their representation is different.

**Comment by rianby64** [comment]
Thanks a lot! You're right! Next time I'll think and read twice before send a question.
