### ISSUE TITLE
Scenario.Title vs Name

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/gherkin3#19]
Similar to Issue #18, but this is the first line of  Scenario, Scenario Outline, Background, Examples, Feature, after the keyword.

In the original discussions we agreed on `title` (https://groups.google.com/d/msg/cukes-devs/RCnkmXsLQEs/GJgi0_bk_K0J) but later in the cucumber-core discussions switched to `name` (https://groups.google.com/d/msg/cukes-devs/YAdxutcTlYA/Bta1gKfVH0sJ) with the argument that _title_ is too formal. 

Now the C# code uses `title` the others `name`. We should consolidate this.

Title or Name?

/CC @aslakhellesoy @tooky @mattwynne

**Comment by aslakhellesoy** [comment]
Thanks for digging up the old conversations @gasparnagy! I just read both of them - what a great discussion!

One of the tricks we try to teach people is to name their scenarios like [friends episodes](http://en.wikipedia.org/wiki/List_of_Friends_episodes) - *The one where ...* or *The one with ...*, because it helps keep scenarios more *focussed*.

Sitcom episodes have *titles* (just like books), so that's an argument for using the word *title*. However, in conversations I think most people would say *The name of the episode is ...*, so that's an argument for using *name*.

Also, since the book uses *name* I think we should stick with *name*.

Ok?

**Comment by mattwynne** [comment]
name

**Comment by gasparnagy** [comment]
Makes sense. I'll fix the C# one. The others don't need any change as far as I see.

**Comment by gasparnagy** [comment]
fixed
