### ISSUE TITLE
Fix gherkin-go travis build

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin3#22]
Hi @muhqu can you take a look at https://travis-ci.org/cucumber/gherkin-go and figure out why that's failing?

Thanks!
Aslak

**Comment by muhqu** [comment]
@aslakhellesoy what do you think of https://github.com/cucumber/gherkin-go/issues/1?

I'm not sure it is the right fix... Maybe we should change the Makefiles so that `make` inside the language repository doesn't generate the parser. So that only the Makefile in the master-repository generates the parser and dialects etc...

I think there is no benefit of having the mono-based parser generator run in every split repository...

what do you think?

**Comment by muhqu** [comment]
@aslakhellesoy …let's see what 2bda1e0c5205bf6e96ff54cfdd594e935c45e469...90e81e2e274550289c26e92a4101fda0fbfcc014 has to offer... see [travis build](https://travis-ci.org/cucumber/gherkin-go/builds/57604959)

**Comment by muhqu** [comment]
:checkered_flag:
